env:
    DEVICE_CODENAME: juice
    BUILD_USER: juice
    BUILD_HOST: nfs-project
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    TG_TOKEN: "ENCRYPTED[ce4f7e889159d16472847d164bbc8b503b90a9560a56f6c71641a3d16bc0f605fa23fe1643e71850b373ec43692d90b0]"
    TG_CHAT_ID: "ENCRYPTED[470457b508c083087e2cccc7b464cdb0a0d76b63e340637d680998cef3c185ad10e79e0bbbfc3011a4d23c0e0087adfb]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 8
      memory: 32G

  Sync_script:
  #    - ./download.sh

  Build_kernel_Clang_script:
  #    - ./clang.sh

  Notif_script:
      - ./done.sh
